export { default as CloseIcon } from './CloseIcon.vue'
export { default as MainIcon } from './MainIcon.vue'
export { default as MenuIcon } from './MenuIcon.vue'
export { default as EditIcon } from './EditIcon.vue'
export { default as CopyIcon } from './CopyIcon.vue'